# Generated by Django 5.2.15 on 2026-07-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_regime_detection_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignResearchContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_level', models.IntegerField(blank=True, null=True)),
                ('height_above_ground_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('direct_connection_to_soil', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('room_volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('room_volume_source', models.CharField(blank=True, choices=[('CALCULATED', 'Calculated'), ('REPORTED', 'Reported'), ('ESTIMATED', 'Estimated'), ('USER_SELECTED', 'User selected'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('dominant_material', models.CharField(blank=True, max_length=160)),
                ('sensor_height_m', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('distance_from_nearest_opening_m', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('sensor_moved_during_campaign', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('event_log_availability', models.CharField(blank=True, choices=[('DOCUMENTED', 'Documented'), ('PARTIAL', 'Partial'), ('UNAVAILABLE', 'Unavailable'), ('NATURALISTIC_FREQUENT_INTERVENTIONS', 'Naturalistic frequent interventions')], max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('evidence_status', models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('ASSUMED', 'Assumed'), ('ESTIMATED', 'Estimated'), ('PROVIDED', 'Provided'), ('VERIFIED', 'Verified')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_context', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'campaign research context',
                'verbose_name_plural': 'campaign research contexts',
            },
        ),
    ]
